# Site settings
title: gregloesch - blog
email: greg@gregloesch.com
description: musings from a dev
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gregloesch.com" 

# Build settings
markdown: kramdown

# Custom settings
excerpt_separator: <!--more-->

plugins:
  - jekyll-gist
